/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios.Pagos;

import Clases.dbConnection;
import FormularioIGP.frmPrincipal;
import FormulariosCrucero.clsVariablesViaje;
import FormulariosCrucero.frmSeleccionClientes;
import java.net.URL;
import java.sql.*;
import javax.swing.JRadioButton;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Hacknel
 */
public class frmPagos extends javax.swing.JFrame {

    /**
     * Creates new form frmPagos
     */
    public frmPagos() {
        initComponents();
    }

    PreparedStatement ps;
    clsVariablesViaje variablesViaje = new clsVariablesViaje();
    DefaultTableModel modelCliente = variablesViaje.getModel1();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtNumFactura = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPuertoPartida = new javax.swing.JTextField();
        btnConsultarPersonas = new javax.swing.JButton();
        txtFechaFin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        txtFechaInicio = new javax.swing.JTextField();
        txtPuertoDestino = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNombre2 = new javax.swing.JTextField();
        btnIniciarSesion1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNivelCubierta = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtNumeroCamarote = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtNombreCrucero = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        btnIniciarSesion3 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lblSubTotal = new javax.swing.JLabel();
        lblISV = new javax.swing.JLabel();
        lblDescuento = new javax.swing.JLabel();
        lblPropina = new javax.swing.JLabel();
        lblTotalPagar = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel33 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PAGOS");
        setMinimumSize(new java.awt.Dimension(1635, 1035));
        setName("frmPago"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 79, 129));
        jPanel1.setMaximumSize(new java.awt.Dimension(1635, 1035));
        jPanel1.setMinimumSize(new java.awt.Dimension(1635, 1035));
        jPanel1.setPreferredSize(new java.awt.Dimension(1635, 1035));
        jPanel1.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Doppio One", 1, 40)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 204, 51));
        jLabel7.setText("DESGLOSE");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(323, 603, 200, 51);

        txtNumFactura.setEditable(false);
        txtNumFactura.setFont(new java.awt.Font("Doppio One", 0, 16)); // NOI18N
        jPanel1.add(txtNumFactura);
        txtNumFactura.setBounds(314, 194, 102, 26);

        jLabel2.setFont(new java.awt.Font("Doppio One", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Número de Factura");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(116, 193, 180, 26);

        jLabel3.setFont(new java.awt.Font("Doppio One", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha Inicio");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(961, 193, 110, 26);

        txtPuertoPartida.setEditable(false);
        txtPuertoPartida.setFont(new java.awt.Font("Doppio One", 0, 16)); // NOI18N
        jPanel1.add(txtPuertoPartida);
        txtPuertoPartida.setBounds(961, 301, 182, 30);

        btnConsultarPersonas.setBackground(new java.awt.Color(255, 204, 51));
        btnConsultarPersonas.setFont(new java.awt.Font("Doppio One", 0, 18)); // NOI18N
        btnConsultarPersonas.setForeground(new java.awt.Color(0, 0, 0));
        btnConsultarPersonas.setText("CONSULTAR PERSONAS");
        btnConsultarPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarPersonasActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultarPersonas);
        btnConsultarPersonas.setBounds(236, 353, 285, 42);

        txtFechaFin.setEditable(false);
        txtFechaFin.setFont(new java.awt.Font("Doppio One", 0, 16)); // NOI18N
        jPanel1.add(txtFechaFin);
        txtFechaFin.setBounds(1189, 225, 130, 30);

        jLabel4.setFont(new java.awt.Font("Doppio One", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha Fin");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(1189, 193, 89, 26);

        jLabel5.setFont(new java.awt.Font("Doppio One", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre cliente");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(116, 269, 142, 26);

        jLabel6.setFont(new java.awt.Font("Doppio One", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Puerto de partida");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(961, 269, 164, 26);

        txtNombre1.setEditable(false);
        txtNombre1.setFont(new java.awt.Font("Doppio One", 0, 16)); // NOI18N
        jPanel1.add(txtNombre1);
        txtNombre1.setBounds(116, 301, 255, 30);

        txtFechaInicio.setEditable(false);
        txtFechaInicio.setFont(new java.awt.Font("Doppio One", 0, 16)); // NOI18N
        jPanel1.add(txtFechaInicio);
        txtFechaInicio.setBounds(961, 225, 130, 30);

        txtPuertoDestino.setEditable(false);
        txtPuertoDestino.setFont(new java.awt.Font("Doppio One", 0, 16)); // NOI18N
        jPanel1.add(txtPuertoDestino);
        txtPuertoDestino.setBounds(1189, 301, 182, 30);

        jLabel8.setFont(new java.awt.Font("Doppio One", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Puerto de destino");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(1189, 269, 165, 26);

        txtNombre2.setEditable(false);
        txtNombre2.setFont(new java.awt.Font("Doppio One", 0, 16)); // NOI18N
        jPanel1.add(txtNombre2);
        txtNombre2.setBounds(389, 301, 255, 30);

        btnIniciarSesion1.setBackground(new java.awt.Color(255, 204, 51));
        btnIniciarSesion1.setFont(new java.awt.Font("Doppio One", 0, 18)); // NOI18N
        btnIniciarSesion1.setForeground(new java.awt.Color(0, 0, 0));
        btnIniciarSesion1.setText("PAGAR");
        jPanel1.add(btnIniciarSesion1);
        btnIniciarSesion1.setBounds(1416, 926, 195, 63);

        jLabel9.setFont(new java.awt.Font("Doppio One", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Correo electronico");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(116, 432, 168, 26);

        txtCorreo.setEditable(false);
        txtCorreo.setFont(new java.awt.Font("Doppio One", 0, 16)); // NOI18N
        jPanel1.add(txtCorreo);
        txtCorreo.setBounds(116, 464, 255, 30);

        jLabel10.setFont(new java.awt.Font("Doppio One", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Número de telefóno");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(116, 508, 186, 26);

        txtTel.setEditable(false);
        txtTel.setFont(new java.awt.Font("Doppio One", 0, 16)); // NOI18N
        jPanel1.add(txtTel);
        txtTel.setBounds(116, 540, 255, 30);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(6, 593, 1623, 10);

        jLabel11.setFont(new java.awt.Font("Doppio One", 1, 40)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 204, 51));
        jLabel11.setText("PAGO DE PAQUETE");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(624, 49, 357, 51);

        jLabel13.setFont(new java.awt.Font("Doppio One", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nivel de cubierta");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(961, 451, 158, 26);

        txtNivelCubierta.setEditable(false);
        txtNivelCubierta.setFont(new java.awt.Font("Doppio One", 0, 16)); // NOI18N
        txtNivelCubierta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNivelCubiertaActionPerformed(evt);
            }
        });
        jPanel1.add(txtNivelCubierta);
        txtNivelCubierta.setBounds(961, 483, 182, 30);

        jLabel14.setFont(new java.awt.Font("Doppio One", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Número de camarote");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(1200, 451, 197, 26);

        txtNumeroCamarote.setEditable(false);
        txtNumeroCamarote.setFont(new java.awt.Font("Doppio One", 0, 16)); // NOI18N
        jPanel1.add(txtNumeroCamarote);
        txtNumeroCamarote.setBounds(1200, 483, 169, 30);

        jLabel15.setFont(new java.awt.Font("Doppio One", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Nombre crucero");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(960, 360, 147, 26);

        txtNombreCrucero.setEditable(false);
        txtNombreCrucero.setFont(new java.awt.Font("Doppio One", 0, 16)); // NOI18N
        jPanel1.add(txtNombreCrucero);
        txtNombreCrucero.setBounds(960, 390, 171, 30);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(798, 604, 10, 426);

        jLabel16.setFont(new java.awt.Font("Doppio One", 1, 40)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 204, 51));
        jLabel16.setText("PAGO");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(1165, 621, 108, 51);

        btnIniciarSesion3.setBackground(new java.awt.Color(255, 204, 51));
        btnIniciarSesion3.setFont(new java.awt.Font("Doppio One", 0, 18)); // NOI18N
        btnIniciarSesion3.setForeground(new java.awt.Color(0, 0, 0));
        btnIniciarSesion3.setText("ATRAS");
        jPanel1.add(btnIniciarSesion3);
        btnIniciarSesion3.setBounds(15, 927, 195, 63);

        buttonGroup1.add(jRadioButton1);
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(874, 713, 28, 42);

        buttonGroup1.add(jRadioButton2);
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(1018, 713, 28, 42);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/logoMaster.png"))); // NOI18N
        jPanel1.add(jLabel17);
        jLabel17.setBounds(1058, 713, 65, 42);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/logoVisa.png"))); // NOI18N
        jPanel1.add(jLabel18);
        jLabel18.setBounds(908, 713, 65, 42);

        jLabel19.setFont(new java.awt.Font("Doppio One", 0, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Titular de la tarjeta");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(874, 773, 184, 26);

        jTextField13.setFont(new java.awt.Font("Doppio One", 0, 16)); // NOI18N
        jPanel1.add(jTextField13);
        jTextField13.setBounds(874, 804, 249, 30);

        jTextField14.setFont(new java.awt.Font("Doppio One", 0, 16)); // NOI18N
        jPanel1.add(jTextField14);
        jTextField14.setBounds(874, 871, 249, 30);

        jLabel20.setFont(new java.awt.Font("Doppio One", 0, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Número de tarjeta");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(874, 839, 173, 26);

        jLabel21.setFont(new java.awt.Font("Doppio One", 0, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Vencimiento");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(1173, 773, 117, 26);

        jComboBox1.setFont(new java.awt.Font("Doppio One", 0, 13)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(1173, 805, 46, 28);

        jComboBox2.setFont(new java.awt.Font("Doppio One", 0, 13)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(1230, 805, 60, 28);

        jLabel22.setFont(new java.awt.Font("Doppio One", 0, 20)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("CVC");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(1173, 839, 37, 26);

        jTextField15.setFont(new java.awt.Font("Doppio One", 0, 16)); // NOI18N
        jPanel1.add(jTextField15);
        jTextField15.setBounds(1173, 871, 63, 30);

        jLabel23.setFont(new java.awt.Font("Doppio One", 0, 20)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Subtotal:");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(239, 689, 83, 26);

        jLabel24.setFont(new java.awt.Font("Doppio One", 0, 20)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("ISV:");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(288, 733, 34, 26);

        jLabel25.setFont(new java.awt.Font("Doppio One", 0, 20)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Descuento:");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(221, 777, 101, 26);

        jLabel26.setFont(new java.awt.Font("Doppio One", 0, 20)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Total a Pagar: ");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(279, 887, 135, 26);

        jLabel27.setFont(new java.awt.Font("Doppio One", 0, 20)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Propina:");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(246, 821, 76, 26);

        lblSubTotal.setFont(new java.awt.Font("Doppio One", 0, 20)); // NOI18N
        lblSubTotal.setForeground(new java.awt.Color(255, 204, 0));
        lblSubTotal.setText("16000.00");
        jPanel1.add(lblSubTotal);
        lblSubTotal.setBounds(340, 689, 88, 26);

        lblISV.setFont(new java.awt.Font("Doppio One", 0, 20)); // NOI18N
        lblISV.setForeground(new java.awt.Color(255, 204, 0));
        lblISV.setText("2400.00");
        jPanel1.add(lblISV);
        lblISV.setBounds(350, 733, 78, 26);

        lblDescuento.setFont(new java.awt.Font("Doppio One", 0, 20)); // NOI18N
        lblDescuento.setForeground(new java.awt.Color(255, 204, 0));
        lblDescuento.setText("0.00");
        jPanel1.add(lblDescuento);
        lblDescuento.setBounds(385, 777, 43, 26);

        lblPropina.setFont(new java.awt.Font("Doppio One", 0, 20)); // NOI18N
        lblPropina.setForeground(new java.awt.Color(255, 204, 0));
        lblPropina.setText("1600.00");
        jPanel1.add(lblPropina);
        lblPropina.setBounds(353, 821, 75, 26);

        lblTotalPagar.setFont(new java.awt.Font("Doppio One", 0, 20)); // NOI18N
        lblTotalPagar.setForeground(new java.awt.Color(255, 204, 0));
        lblTotalPagar.setText("20000.00");
        jPanel1.add(lblTotalPagar);
        lblTotalPagar.setBounds(441, 887, 93, 26);

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Doppio One", 0, 20)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Efectivo");
        jPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(1173, 713, 106, 42);

        jLabel33.setFont(new java.awt.Font("Doppio One", 0, 20)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Cambio en efectivo");
        jPanel1.add(jLabel33);
        jLabel33.setBounds(1370, 840, 190, 26);

        jTextField16.setFont(new java.awt.Font("Doppio One", 0, 16)); // NOI18N
        jPanel1.add(jTextField16);
        jTextField16.setBounds(1365, 804, 130, 30);

        jTextField17.setEditable(false);
        jTextField17.setFont(new java.awt.Font("Doppio One", 0, 16)); // NOI18N
        jPanel1.add(jTextField17);
        jTextField17.setBounds(1370, 870, 120, 26);

        jLabel34.setFont(new java.awt.Font("Doppio One", 0, 20)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Cantidad Recibida");
        jPanel1.add(jLabel34);
        jLabel34.setBounds(1365, 773, 170, 26);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/imgBotonHome (2).png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(1550, 10, 75, 68);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNivelCubiertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNivelCubiertaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNivelCubiertaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        cargarDatos(modelCliente.getValueAt(0, 0).toString(), variablesViaje.getCodigoViaje());
        
    }//GEN-LAST:event_formWindowOpened

    private void btnConsultarPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPersonasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarPersonasActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.setVisible(false);
        new frmPrincipal().setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void cargarDatos(String identidadCliente, int idViaje) {
        
        try{
            //Se obtienen los datos del cliente
            ps = dbConnection.dbConexion().prepareStatement("SELECT nombres n1, apellidos n2, telefono tl, correoElectronico ce FROM clientes WHERE identidadCliente = ?");
            ps.setString(1, identidadCliente);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                txtNombre1.setText(rs.getString("n1"));
                txtNombre2.setText(rs.getString("n2"));
                txtTel.setText(rs.getString("tl"));
                txtCorreo.setText(rs.getString("ce"));
            }
            
            //se obtienen los datos de factura
            ps = dbConnection.dbConexion().prepareStatement("SELECT MAX(codigoFactura)cf FROM [dbo].[facturaFinal]");
            rs = null;
            rs = ps.executeQuery();
            if(rs.next()){
                txtNumFactura.setText("" + (rs.getInt("cf") + 1));
            }
            
            //se obtienen los datos de viaje
            ps = dbConnection.dbConexion().prepareStatement("SELECT B.nombreBuque as nb, C.nombrePuerto as np, D.nombreDestino as nd, A.fechaSalida as fs, A.fechaRegreso as fr FROM [dbo].[viajesDisponibles] A INNER JOIN [dbo].[buques] B  ON A.codigoBuque = B.codigoBuque INNER JOIN [dbo].[puertosSalida] C ON A.codigoPuertoSalida = C.codigoPuerto INNER JOIN [dbo].[destinosTuristicos] D ON A.codigoDestino = D.codigoDestino WHERE A.idViaje = ?");
            ps.setInt(1, idViaje);
            ResultSet result = ps.executeQuery();
            if (result.next()) {
                txtNombreCrucero.setText(result.getString("nb"));
                txtPuertoPartida.setText(result.getString("np"));
                txtPuertoDestino.setText(result.getString("nd"));
                txtFechaInicio.setText(result.getString("fs"));
                txtFechaFin.setText(result.getString("fr"));
                txtNivelCubierta.setText("" + variablesViaje.getNivelBarco());
                txtNumeroCamarote.setText("" + variablesViaje.getNumeroCamarote());

            }
            
        }catch(SQLException ex){
            System.out.println(""+ex.getMessage());
        }

    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPagos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarPersonas;
    private javax.swing.JButton btnIniciarSesion1;
    private javax.swing.JButton btnIniciarSesion3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JLabel lblDescuento;
    private javax.swing.JLabel lblISV;
    private javax.swing.JLabel lblPropina;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblTotalPagar;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JTextField txtFechaInicio;
    private javax.swing.JTextField txtNivelCubierta;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtNombre2;
    private javax.swing.JTextField txtNombreCrucero;
    private javax.swing.JTextField txtNumFactura;
    private javax.swing.JTextField txtNumeroCamarote;
    private javax.swing.JTextField txtPuertoDestino;
    private javax.swing.JTextField txtPuertoPartida;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
