/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormulariosCrucero;

/**
 *
 * @author OscarM
 */
public class frmVistaCamarotes extends javax.swing.JFrame {

    /**
     * Creates new form frmVistaCamarotes
     */
    public frmVistaCamarotes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 79, 129));
        jPanel1.setPreferredSize(new java.awt.Dimension(1635, 1035));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Avenir LT Std 65 Medium", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 51));
        jLabel1.setText("CAMAROTES - NIVEL 2");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(600, 70, 550, 49);

        jButton1.setBackground(new java.awt.Color(255, 204, 51));
        jButton1.setFont(new java.awt.Font("Avenir LT Std 65 Medium", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("ATRAS");
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 970, 210, 60);

        jButton28.setBackground(new java.awt.Color(255, 0, 0));
        jButton28.setFont(new java.awt.Font("Doppio One", 0, 8)); // NOI18N
        jButton28.setHideActionText(true);
        jButton28.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton28);
        jButton28.setBounds(990, 351, 40, 40);

        jButton2.setBackground(new java.awt.Color(255, 204, 51));
        jButton2.setFont(new java.awt.Font("Avenir LT Std 65 Medium", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("SIGUIENTE");
        jPanel1.add(jButton2);
        jButton2.setBounds(1420, 970, 210, 60);

        jButton25.setBackground(new java.awt.Color(255, 0, 0));
        jButton25.setHideActionText(true);
        jButton25.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton25);
        jButton25.setBounds(756, 420, 40, 30);

        jButton27.setBackground(new java.awt.Color(255, 0, 0));
        jButton27.setFont(new java.awt.Font("Doppio One", 0, 8)); // NOI18N
        jButton27.setHideActionText(true);
        jButton27.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton27);
        jButton27.setBounds(977, 520, 40, 40);

        jButton29.setBackground(new java.awt.Color(255, 0, 0));
        jButton29.setFont(new java.awt.Font("Doppio One", 0, 8)); // NOI18N
        jButton29.setHideActionText(true);
        jButton29.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton29);
        jButton29.setBounds(730, 351, 40, 40);

        jButton30.setBackground(new java.awt.Color(255, 0, 0));
        jButton30.setFont(new java.awt.Font("Doppio One", 0, 8)); // NOI18N
        jButton30.setHideActionText(true);
        jButton30.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton30);
        jButton30.setBounds(910, 351, 40, 40);

        jButton31.setBackground(new java.awt.Color(255, 0, 0));
        jButton31.setFont(new java.awt.Font("Doppio One", 0, 8)); // NOI18N
        jButton31.setHideActionText(true);
        jButton31.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton31);
        jButton31.setBounds(839, 351, 40, 40);

        jButton32.setBackground(new java.awt.Color(255, 0, 0));
        jButton32.setFont(new java.awt.Font("Doppio One", 0, 8)); // NOI18N
        jButton32.setText("   ");
        jButton32.setToolTipText("");
        jButton32.setHideActionText(true);
        jButton32.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton32);
        jButton32.setBounds(676, 351, 40, 40);

        jButton33.setBackground(new java.awt.Color(255, 0, 0));
        jButton33.setFont(new java.awt.Font("Doppio One", 0, 8)); // NOI18N
        jButton33.setText("   ");
        jButton33.setToolTipText("");
        jButton33.setHideActionText(true);
        jButton33.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton33);
        jButton33.setBounds(621, 351, 40, 40);

        jButton35.setBackground(new java.awt.Color(255, 0, 0));
        jButton35.setFont(new java.awt.Font("Doppio One", 0, 8)); // NOI18N
        jButton35.setHideActionText(true);
        jButton35.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton35);
        jButton35.setBounds(785, 351, 40, 40);

        jButton36.setBackground(new java.awt.Color(255, 0, 0));
        jButton36.setFont(new java.awt.Font("Doppio One", 0, 8)); // NOI18N
        jButton36.setText("  ");
        jButton36.setHideActionText(true);
        jButton36.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton36);
        jButton36.setBounds(458, 351, 40, 40);

        jButton37.setBackground(new java.awt.Color(255, 0, 0));
        jButton37.setFont(new java.awt.Font("Doppio One", 0, 8)); // NOI18N
        jButton37.setText("  ");
        jButton37.setHideActionText(true);
        jButton37.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton37);
        jButton37.setBounds(403, 351, 40, 40);

        jButton38.setBackground(new java.awt.Color(255, 0, 0));
        jButton38.setFont(new java.awt.Font("Doppio One", 0, 8)); // NOI18N
        jButton38.setText("  ");
        jButton38.setHideActionText(true);
        jButton38.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton38);
        jButton38.setBounds(333, 520, 40, 40);

        jButton39.setBackground(new java.awt.Color(255, 0, 0));
        jButton39.setFont(new java.awt.Font("Doppio One", 0, 8)); // NOI18N
        jButton39.setText("   ");
        jButton39.setToolTipText("");
        jButton39.setHideActionText(true);
        jButton39.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton39);
        jButton39.setBounds(566, 351, 40, 40);

        jButton40.setBackground(new java.awt.Color(255, 0, 0));
        jButton40.setFont(new java.awt.Font("Doppio One", 0, 8)); // NOI18N
        jButton40.setText("  ");
        jButton40.setHideActionText(true);
        jButton40.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton40);
        jButton40.setBounds(512, 351, 40, 40);

        jButton41.setBackground(new java.awt.Color(255, 0, 0));
        jButton41.setFont(new java.awt.Font("Doppio One", 0, 8)); // NOI18N
        jButton41.setText("  ");
        jButton41.setHideActionText(true);
        jButton41.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton41);
        jButton41.setBounds(403, 520, 40, 40);

        jButton42.setBackground(new java.awt.Color(255, 0, 0));
        jButton42.setFont(new java.awt.Font("Doppio One", 0, 8)); // NOI18N
        jButton42.setText("   ");
        jButton42.setToolTipText("");
        jButton42.setHideActionText(true);
        jButton42.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton42);
        jButton42.setBounds(458, 520, 40, 40);

        jButton43.setBackground(new java.awt.Color(255, 0, 0));
        jButton43.setFont(new java.awt.Font("Doppio One", 0, 8)); // NOI18N
        jButton43.setText("   ");
        jButton43.setToolTipText("");
        jButton43.setHideActionText(true);
        jButton43.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton43);
        jButton43.setBounds(512, 520, 40, 40);

        jButton44.setBackground(new java.awt.Color(255, 0, 0));
        jButton44.setFont(new java.awt.Font("Doppio One", 0, 8)); // NOI18N
        jButton44.setText("   ");
        jButton44.setToolTipText("");
        jButton44.setHideActionText(true);
        jButton44.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton44);
        jButton44.setBounds(566, 520, 40, 40);

        jButton45.setBackground(new java.awt.Color(255, 0, 0));
        jButton45.setFont(new java.awt.Font("Doppio One", 0, 8)); // NOI18N
        jButton45.setText("   ");
        jButton45.setToolTipText("");
        jButton45.setHideActionText(true);
        jButton45.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton45);
        jButton45.setBounds(621, 520, 40, 40);

        jButton46.setBackground(new java.awt.Color(255, 0, 0));
        jButton46.setFont(new java.awt.Font("Doppio One", 0, 8)); // NOI18N
        jButton46.setHideActionText(true);
        jButton46.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton46);
        jButton46.setBounds(676, 520, 40, 40);

        jButton47.setBackground(new java.awt.Color(255, 0, 0));
        jButton47.setFont(new java.awt.Font("Doppio One", 0, 8)); // NOI18N
        jButton47.setHideActionText(true);
        jButton47.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton47);
        jButton47.setBounds(730, 520, 40, 40);

        jButton48.setBackground(new java.awt.Color(255, 0, 0));
        jButton48.setFont(new java.awt.Font("Doppio One", 0, 8)); // NOI18N
        jButton48.setHideActionText(true);
        jButton48.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton48);
        jButton48.setBounds(785, 520, 40, 40);

        jButton49.setBackground(new java.awt.Color(255, 0, 0));
        jButton49.setFont(new java.awt.Font("Doppio One", 0, 8)); // NOI18N
        jButton49.setHideActionText(true);
        jButton49.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton49);
        jButton49.setBounds(839, 520, 40, 40);

        jButton50.setBackground(new java.awt.Color(255, 0, 0));
        jButton50.setFont(new java.awt.Font("Doppio One", 0, 8)); // NOI18N
        jButton50.setText("  ");
        jButton50.setHideActionText(true);
        jButton50.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton50);
        jButton50.setBounds(333, 351, 40, 40);

        jButton26.setBackground(new java.awt.Color(255, 0, 0));
        jButton26.setFont(new java.awt.Font("Doppio One", 0, 8)); // NOI18N
        jButton26.setHideActionText(true);
        jButton26.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton26);
        jButton26.setBounds(910, 520, 40, 40);

        jButton51.setBackground(new java.awt.Color(255, 0, 0));
        jButton51.setHideActionText(true);
        jButton51.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton51);
        jButton51.setBounds(808, 420, 40, 30);

        jButton52.setBackground(new java.awt.Color(255, 0, 0));
        jButton52.setHideActionText(true);
        jButton52.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton52ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton52);
        jButton52.setBounds(702, 460, 40, 30);

        jButton53.setBackground(new java.awt.Color(255, 0, 0));
        jButton53.setHideActionText(true);
        jButton53.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton53ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton53);
        jButton53.setBounds(756, 460, 40, 30);

        jButton54.setBackground(new java.awt.Color(255, 0, 0));
        jButton54.setHideActionText(true);
        jButton54.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton54);
        jButton54.setBounds(808, 460, 40, 30);

        jButton55.setBackground(new java.awt.Color(255, 0, 0));
        jButton55.setHideActionText(true);
        jButton55.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton55);
        jButton55.setBounds(860, 420, 40, 30);

        jButton56.setBackground(new java.awt.Color(255, 0, 0));
        jButton56.setHideActionText(true);
        jButton56.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton56ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton56);
        jButton56.setBounds(860, 460, 40, 30);

        jButton57.setBackground(new java.awt.Color(255, 0, 0));
        jButton57.setHideActionText(true);
        jButton57.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton57);
        jButton57.setBounds(1125, 445, 50, 20);

        jButton58.setBackground(new java.awt.Color(255, 0, 0));
        jButton58.setHideActionText(true);
        jButton58.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton58);
        jButton58.setBounds(1144, 380, 30, 40);

        jButton66.setBackground(new java.awt.Color(255, 0, 0));
        jButton66.setHideActionText(true);
        jButton66.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton66);
        jButton66.setBounds(702, 420, 40, 30);

        jButton67.setBackground(new java.awt.Color(255, 0, 0));
        jButton67.setHideActionText(true);
        jButton67.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton67);
        jButton67.setBounds(1056, 445, 50, 20);

        jButton59.setBackground(new java.awt.Color(255, 0, 0));
        jButton59.setHideActionText(true);
        jButton59.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton59);
        jButton59.setBounds(1058, 380, 30, 40);

        jButton60.setBackground(new java.awt.Color(255, 0, 0));
        jButton60.setHideActionText(true);
        jButton60.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton60);
        jButton60.setBounds(1186, 380, 30, 40);

        jButton61.setBackground(new java.awt.Color(255, 0, 0));
        jButton61.setHideActionText(true);
        jButton61.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton61);
        jButton61.setBounds(1030, 490, 30, 40);

        jButton62.setBackground(new java.awt.Color(255, 0, 0));
        jButton62.setHideActionText(true);
        jButton62.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton62);
        jButton62.setBounds(1117, 490, 30, 40);

        jButton63.setBackground(new java.awt.Color(255, 0, 0));
        jButton63.setHideActionText(true);
        jButton63.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton63);
        jButton63.setBounds(1100, 380, 30, 40);

        jButton64.setBackground(new java.awt.Color(255, 0, 0));
        jButton64.setHideActionText(true);
        jButton64.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton64);
        jButton64.setBounds(1160, 490, 30, 40);

        jButton65.setBackground(new java.awt.Color(255, 0, 0));
        jButton65.setHideActionText(true);
        jButton65.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton65);
        jButton65.setBounds(1073, 490, 30, 40);

        jLabel5.setFont(new java.awt.Font("Doppio One", 0, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\OscarM\\Documents\\1 PERIODO 2021\\Programacion Multiplataforma\\III Parcial\\mapa2Num.png")); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(240, 250, 1210, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton52ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton52ActionPerformed

    private void jButton53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton53ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton53ActionPerformed

    private void jButton56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton56ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton56ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVistaCamarotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVistaCamarotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVistaCamarotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVistaCamarotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVistaCamarotes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
