/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormularioIGP;

/**
 *
 * @author CLT_56
 */
public class frmIGP extends javax.swing.JFrame {

    /**
     * Creates new form frmIGP
     */
    public frmIGP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panMenu = new javax.swing.JPanel();
        lblBotones = new javax.swing.JLabel();
        btnViajesDisponibles = new javax.swing.JButton();
        btnDestinosTuristicos = new javax.swing.JButton();
        btnFactura = new javax.swing.JButton();
        panEncabezado = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        btnMaximizar = new javax.swing.JButton();
        btnMinimizar1 = new javax.swing.JButton();
        panSubMenu = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        btnUsuario2 = new javax.swing.JButton();
        btnUsuario3 = new javax.swing.JButton();
        btnUsuario4 = new javax.swing.JButton();
        btnUsuario5 = new javax.swing.JButton();
        btnUsuario1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panMenu.setBackground(new java.awt.Color(0, 79, 129));
        panMenu.setForeground(new java.awt.Color(0, 114, 187));
        panMenu.setPreferredSize(new java.awt.Dimension(1635, 1035));
        panMenu.setLayout(null);

        lblBotones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/cruceroBotones.png"))); // NOI18N
        panMenu.add(lblBotones);
        lblBotones.setBounds(40, 150, 1560, 620);

        btnViajesDisponibles.setBackground(new java.awt.Color(255, 255, 255));
        btnViajesDisponibles.setFont(new java.awt.Font("Avenir LT Std 65 Medium", 1, 36)); // NOI18N
        btnViajesDisponibles.setForeground(new java.awt.Color(0, 0, 0));
        btnViajesDisponibles.setText("VIAJES DISPONIBLES");
        btnViajesDisponibles.setBorder(null);
        panMenu.add(btnViajesDisponibles);
        btnViajesDisponibles.setBounds(40, 400, 1550, 100);

        btnDestinosTuristicos.setBackground(new java.awt.Color(255, 255, 255));
        btnDestinosTuristicos.setFont(new java.awt.Font("Avenir LT Std 65 Medium", 1, 36)); // NOI18N
        btnDestinosTuristicos.setForeground(new java.awt.Color(0, 0, 0));
        btnDestinosTuristicos.setText("DESTINOS TURISTICOS");
        btnDestinosTuristicos.setBorder(null);
        panMenu.add(btnDestinosTuristicos);
        btnDestinosTuristicos.setBounds(40, 510, 1550, 100);

        btnFactura.setBackground(new java.awt.Color(255, 255, 255));
        btnFactura.setFont(new java.awt.Font("Avenir LT Std 65 Medium", 1, 36)); // NOI18N
        btnFactura.setForeground(new java.awt.Color(0, 0, 0));
        btnFactura.setText("FACTURA ");
        btnFactura.setBorder(null);
        btnFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturaActionPerformed(evt);
            }
        });
        panMenu.add(btnFactura);
        btnFactura.setBounds(40, 620, 1550, 120);

        panEncabezado.setBackground(new java.awt.Color(13, 54, 118));

        btnCerrar.setBackground(new java.awt.Color(13, 54, 118));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/exitButton45.png"))); // NOI18N
        btnCerrar.setBorder(null);

        btnMaximizar.setBackground(new java.awt.Color(13, 54, 118));
        btnMaximizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/maximize40.png"))); // NOI18N
        btnMaximizar.setBorder(null);
        btnMaximizar.setPreferredSize(new java.awt.Dimension(40, 35));

        btnMinimizar1.setBackground(new java.awt.Color(13, 54, 118));
        btnMinimizar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/minimize40.png"))); // NOI18N
        btnMinimizar1.setBorder(null);

        javax.swing.GroupLayout panEncabezadoLayout = new javax.swing.GroupLayout(panEncabezado);
        panEncabezado.setLayout(panEncabezadoLayout);
        panEncabezadoLayout.setHorizontalGroup(
            panEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panEncabezadoLayout.createSequentialGroup()
                .addContainerGap(1717, Short.MAX_VALUE)
                .addComponent(btnMinimizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMaximizar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCerrar)
                .addGap(41, 41, 41))
        );
        panEncabezadoLayout.setVerticalGroup(
            panEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEncabezadoLayout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addGroup(panEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMinimizar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMaximizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addComponent(btnCerrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panSubMenu.setBackground(new java.awt.Color(13, 54, 118));
        panSubMenu.setPreferredSize(new java.awt.Dimension(255, 0));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Logo BonVoyage Peq 250.png"))); // NOI18N

        btnUsuario2.setBackground(new java.awt.Color(241, 209, 90));
        btnUsuario2.setFont(new java.awt.Font("Avenir LT Std 65 Medium", 1, 20)); // NOI18N
        btnUsuario2.setForeground(new java.awt.Color(0, 0, 0));
        btnUsuario2.setText("CLIENTES");
        btnUsuario2.setBorder(null);

        btnUsuario3.setBackground(new java.awt.Color(241, 209, 90));
        btnUsuario3.setFont(new java.awt.Font("Avenir LT Std 65 Medium", 1, 20)); // NOI18N
        btnUsuario3.setForeground(new java.awt.Color(0, 0, 0));
        btnUsuario3.setText("PUERTOS SALIDA");
        btnUsuario3.setBorder(null);

        btnUsuario4.setBackground(new java.awt.Color(241, 209, 90));
        btnUsuario4.setFont(new java.awt.Font("Avenir LT Std 65 Medium", 1, 20)); // NOI18N
        btnUsuario4.setForeground(new java.awt.Color(0, 0, 0));
        btnUsuario4.setText("BUQUES");
        btnUsuario4.setBorder(null);

        btnUsuario5.setBackground(new java.awt.Color(241, 209, 90));
        btnUsuario5.setFont(new java.awt.Font("Avenir LT Std 65 Medium", 1, 20)); // NOI18N
        btnUsuario5.setForeground(new java.awt.Color(0, 0, 0));
        btnUsuario5.setText("CAMAROTES");
        btnUsuario5.setBorder(null);

        btnUsuario1.setBackground(new java.awt.Color(241, 209, 90));
        btnUsuario1.setFont(new java.awt.Font("Avenir LT Std 65 Medium", 1, 20)); // NOI18N
        btnUsuario1.setForeground(new java.awt.Color(0, 0, 0));
        btnUsuario1.setText("USUARIOS");
        btnUsuario1.setBorder(null);

        javax.swing.GroupLayout panSubMenuLayout = new javax.swing.GroupLayout(panSubMenu);
        panSubMenu.setLayout(panSubMenuLayout);
        panSubMenuLayout.setHorizontalGroup(
            panSubMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
            .addComponent(btnUsuario3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnUsuario2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnUsuario4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnUsuario5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnUsuario1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panSubMenuLayout.setVerticalGroup(
            panSubMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSubMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195)
                .addComponent(btnUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnUsuario4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnUsuario5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnUsuario3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(panSubMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(panMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 1660, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(panEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1085, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addComponent(panSubMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 1040, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addComponent(panMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(panEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFacturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmIGP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmIGP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmIGP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmIGP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmIGP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnDestinosTuristicos;
    private javax.swing.JButton btnFactura;
    private javax.swing.JButton btnMaximizar;
    private javax.swing.JButton btnMinimizar1;
    private javax.swing.JButton btnUsuario1;
    private javax.swing.JButton btnUsuario2;
    private javax.swing.JButton btnUsuario3;
    private javax.swing.JButton btnUsuario4;
    private javax.swing.JButton btnUsuario5;
    private javax.swing.JButton btnViajesDisponibles;
    private javax.swing.JLabel lblBotones;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPanel panEncabezado;
    private javax.swing.JPanel panMenu;
    private javax.swing.JPanel panSubMenu;
    // End of variables declaration//GEN-END:variables
}
